# Generated by Django 2.2 on 2020-03-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_title', models.CharField(max_length=255)),
                ('a_content', models.CharField(max_length=10000)),
                ('a_create_time', models.DateTimeField()),
                ('a_hits', models.IntegerField(blank=True, null=True)),
                ('a_comments', models.IntegerField(blank=True, null=True)),
                ('a_picture', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=20, unique=True)),
                ('c_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_content', models.CharField(max_length=1000)),
                ('c_name', models.CharField(max_length=20)),
                ('a_id', models.IntegerField(blank=True, null=True)),
                ('c_data', models.DateTimeField(blank=True, null=True)),
                ('c_portait', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('t_id', models.IntegerField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'title',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_username', models.CharField(max_length=128)),
                ('u_phone_number', models.CharField(max_length=11)),
                ('u_psd', models.CharField(max_length=50)),
                ('u_email', models.CharField(blank=True, max_length=255, null=True)),
                ('u_isforbiden', models.CharField(blank=True, max_length=1, null=True)),
                ('u_portait', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
